services:
  grafana:
    user: root
    container_name: dynamodb-datasource-grafana
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana}
        grafana_version: ${GRAFANA_VERSION:-11.2.2}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3002:3000/tcp
      - 2347:2345/tcp # delve
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./dist:/var/lib/grafana/plugins/haohanyang-dynamodb-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/haohanyang-dynamodb-datasource
    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.haohanyang-dynamodb-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: haohanyang-dynamodb-datasource
    networks:
      - dynamodb-datasource
  
  localstack:
    container_name: dynamodb-datasource-localstack
    image: localstack/localstack
    ports:
      - 4566:4566 # LocalStack Gateway
      - 127.0.0.1:4510-4559:4510-4559  # external services port range
    environment:
      - DEBUG=${DEBUG:-0}
      - SERVICES=dynamodb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dynamodb-datasource
networks:
  dynamodb-datasource:
    driver: bridge