services:
  grafana:
    user: root
    container_name: haohanyang-dynamodb-datasource
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana}
        grafana_version: ${GRAFANA_VERSION:-11.2.2}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3002:3000/tcp
      - 2347:2345/tcp # delve
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./dist:/var/lib/grafana/plugins/haohanyang-dynamodb-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/haohanyang-dynamodb-datasource
    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.haohanyang-dynamodb-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: haohanyang-dynamodb-datasource
    networks:
      - dynamodb-datasource
  
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8002:8000
    networks:
      - dynamodb-datasource

networks:
  dynamodb-datasource:
    driver: bridge